### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by vinhhust2806** [cosmaadrian/time-enriched-multimodal-depression-detection#1]
Hello author,
I am try to implement your paper, but I have a bug here. Could you give me a help!

No such file or directory: 'datasets/twitter-dates.json'   
I wonder where this file is? I did not see that file in datasets folder. Thank you in advance.

**Comment by bucuram** [comment]
Hi,
Thank you for the interest in our work!

We did not include the dates files in the repository. Two json files were used to store the dates for the Reddit and Twitter data. For generating them you should use the format-reddit-2 and format-twitter from here: [https://github.com/cosmaadrian/time-enriched-multimodal-depression-detection/tree/master/scripts](https://github.com/cosmaadrian/time-enriched-multimodal-depression-detection/tree/master/scripts)

**Comment by vinhhust2806** [comment]
Thank you for your reply. I appreciate that!
